name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
  push:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew build
